### ISSUE TITLE
bug: Z.indexOf is not a function

### ISSUE THREAD

**Issue by Chang1ng** [innocces/dumi-theme-chakra#12]
### Versions

- dumi: "^2.0.2",     "dumi-theme-chakra": "^0.0.7"
- node: 16
- OS: mac10+
- Browser: chrome

![image](https://user-images.githubusercontent.com/6593784/218987442-bb7b1c93-ca49-4f7f-b4f1-fca0cad7c933.png)

**Comment by innocces** [comment]
可以提供一个可复现的仓库么？描述一下是启动就报错还是打包？

**Comment by Chang1ng** [comment]
> 

构建生产包，进行部署，部署访问的时候js报错

**Comment by innocces** [comment]
似乎是因为 umi 中 emotion 的问题. 可以先[配置打在一起](https://github.com/innocces/dumi-theme-chakra/blob/main/example/.dumirc.ts#L24)避规这个问题

**Comment by Chang1ng** [comment]
> 似乎是因为 umi 中 emotion 的问题. 可以先[配置打在一起](https://github.com/innocces/dumi-theme-chakra/blob/main/example/.dumirc.ts#L24)避规这个问题

可以了，点赞

**Comment by innocces** [comment]
> > 似乎是因为 umi 中 emotion 的问题. 可以先[配置打在一起](https://github.com/innocces/dumi-theme-chakra/blob/main/example/.dumirc.ts#L24)避规这个问题
> 
> 
> 
> 可以了，点赞

那先暂时关闭了
