### ISSUE TITLE
bug: 按钮的点击区域错误，padding 部分无法点击

### ISSUE THREAD

**Issue by yutingzhao1991** [innocces/dumi-theme-chakra#16]
### 版本

- dumi-theme-chakra:
- dumi:
- node:
- npm:
- OS:
- Browser:

### 复现步骤

访问官网：https://dumi-theme-chakra.deno.dev/

点击按钮文字外侧 padding 部分，无效。

![image](https://github.com/innocces/dumi-theme-chakra/assets/1061968/26aab928-e101-4161-a9eb-93beeec9a703)

### 你期望的现象？

整个按钮都可以点击

**Comment by innocces** [comment]
#17
