### ISSUE TITLE
can't install it

### ISSUE THREAD

**Issue by zilinR** [innocces/dumi-theme-chakra#2]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/107831844/209281109-1f2a0533-7f43-4cee-8d54-5b959062edba.png">

**Comment by innocces** [comment]
not finish yet! may publish soon!

**Comment by zilinR** [comment]
Very much looking forward to the release of the first version！
💪

**Comment by zilinR** [comment]
我也在成都，可以加个好友😁

**Comment by innocces** [comment]
可以来[隔壁群](https://github.com/innocces/taro-hooks/issues/12#issuecomment-1362268669)玩

**Comment by innocces** [comment]
[v0.0.1](https://github.com/innocces/dumi-theme-chakra/releases/tag/v0.0.1)
