### ISSUE TITLE
bug: 安装了这个包后，即使什么都不做dumi启动后页面也打不开，撤销安装以后又正常了

### ISSUE THREAD

**Issue by mengxinssfd** [innocces/dumi-theme-chakra#20]
### 版本

- dumi-theme-chakra: 0.0.20
- dumi: 2.2.1
- node: 16.16.0
- npm: pnpm
- OS: macOS Catalina  
- Browser: Chrome/114.0.0.0

**Comment by innocces** [comment]
嗯？ 不应该吧。目前跟随仓库的exmaple就是直接使用的。没有问题呀

**Comment by mengxinssfd** [comment]
> 嗯？ 不应该吧。目前跟随仓库的exmaple就是直接使用的。没有问题呀

那就不清楚了，我换其他的主题是没问题的😂

**Comment by innocces** [comment]
> > 嗯？ 不应该吧。目前跟随仓库的exmaple就是直接使用的。没有问题呀
> 
> 那就不清楚了，我换其他的主题是没问题的😂

emmmm~ 那我晚点试试

**Comment by innocces** [comment]
报错信息可以粘一下么

**Comment by mengxinssfd** [comment]
<img width="1436" alt="截屏2023-06-29 14 26 40" src="https://github.com/innocces/dumi-theme-chakra/assets/28827520/84d30bfb-6a74-4cce-8b7b-de7573b3762e">
<img width="1435" alt="截屏2023-06-29 14 26 53" src="https://github.com/innocces/dumi-theme-chakra/assets/28827520/5270f6e2-ca2e-4c49-84df-624b09b295e8">
<img width="1438" alt="截屏2023-06-29 14 27 10" src="https://github.com/innocces/dumi-theme-chakra/assets/28827520/6c752071-4d31-47de-a9bc-5f1e47f3b70d">

**Comment by innocces** [comment]
需要提供一下配置项。我这边直接实例了一个 `dumi` 的 `react library` 的模版. 除了 `warning key` 的报错。没有截图上的报错问题。

**Comment by innocces** [comment]
[`warning key error` ](https://github.com/innocces/dumi-theme-chakra/releases/tag/v0.0.21)

第一个报错已在 `0.0.21` 版本修复
