### ISSUE TITLE
如果英语为第一语言，进行切换以后，其他语言的一级菜单不展示 

### ISSUE THREAD

**Issue by kaqiinono** [innocces/dumi-theme-chakra#22]
如果英语为第一语言，进行切换以后，其他语言的一级菜单不展示。
修改中文为第一语言，切换后，一级菜单始终展示 
### 版本
- dumi-theme-chakra: 0.0.21
- dumi: 2.2.1
- node:
- npm:
- OS:
- Browser:

### 
[dp-components.zip](https://github.com/innocces/dumi-theme-chakra/files/11954354/dp-components.zip)
复现 repo(最好可以提供一个复现的 repo)

**Comment by innocces** [comment]
=。-  mark 一下。周末看下。

建议可以先去掉主题看下默认主题下是否展示正常。主题只是增加了特殊组件渲染而已

**Comment by innocces** [comment]
菜单是使用官方的 [`useNavData`](https://d.umijs.org/theme/api#usenavdata) 获取的. 中文模式下获取到的内容不对. 需要自己检查是否格式或组装错误，若无问题可转到 `dumi` 官方仓库提 issue. 

![1688909429994](https://github.com/innocces/dumi-theme-chakra/assets/38065966/49252655-646d-403f-90f2-cee4c60e5911)
