### ISSUE TITLE
window系统主题里面，加这个就报错。

### ISSUE THREAD

**Issue by anyone-yuren** [innocces/dumi-theme-chakra#23]
### Question
![企业微信截图_16890549061324](https://github.com/innocces/dumi-theme-chakra/assets/14817820/1bcb78fc-bc91-44e7-babb-9d2f8c345431)

### Sample Code
```ts
import { defineConfig } from 'dumi';
import { defineThemeConfig, baseTheme } from 'dumi-theme-chakra';

export default defineConfig({
  devtool: 'cheap-module-source-map',
  themeConfig: {
    // https://github.com/umijs/dumi/issues/1655
    nprogress: false,
    name: '文档',
    logo: '/logo.png',
    ...defineThemeConfig({
      helmetIcon: '🍺',
      settingPanelVisible: true,
      thumbBackground: true,
      brand: baseTheme.colors.teal,
      hero: {
        showVersionBadge: true,
      },
    }),
    footer: `Copyright © ${new Date().getFullYear()} `,
  },
});

```

**Comment by innocces** [comment]
是直接使用 create-dumi 实例化的模版么

**Comment by anyone-yuren** [comment]
是的，mac上没有问题，window系统有问题

**Comment by innocces** [comment]
> 是的，mac上没有问题，window系统有问题

emmmm~ 这个感觉是 chrome 的问题. 周末抽空看下吧

**Comment by innocces** [comment]
![image](https://github.com/innocces/dumi-theme-chakra/assets/38065966/66886e81-9e86-4719-97b1-3dd2b68bb679)
![image](https://github.com/innocces/dumi-theme-chakra/assets/38065966/cd9800ef-30cc-46eb-b2a2-2c7d4286d82a)
使用 windows 加同等配置并未复现
