### ISSUE TITLE
顶部导航栏左边的图标怎么修改成自己的？🥺

### ISSUE THREAD

**Issue by Tsukishima1** [innocces/dumi-theme-chakra#24]

**Comment by innocces** [comment]
https://github.com/innocces/dumi-theme-chakra/blob/cb9b2e681f909bde282f8fb6cc09f37f1f772137/example/.dumirc.ts#L44

**Comment by innocces** [comment]
大部分的配置还是走的 [dumi 的配置](https://d.umijs.org/config)。只是在 dumi 的配置上增加一些[客制化的配置](https://dumi-theme-chakra.pages.dev/guide/advance)。

**Comment by Tsukishima1** [comment]
> 大部分的配置还是走的 [dumi 的配置](https://d.umijs.org/config)。只是在 dumi 的配置上增加一些[客制化的配置](https://dumi-theme-chakra.pages.dev/guide/advance)。

感谢

**Comment by Tsukishima1** [comment]
> 大部分的配置还是走的 [dumi 的配置](https://d.umijs.org/config)。只是在 dumi 的配置上增加一些[客制化的配置](https://dumi-theme-chakra.pages.dev/guide/advance)。

佬我想再问一下怎么做到只修改亮色模式下代码段的背景颜色🥺我试图用`[data-theme='light']`和`!important`写但是没有生效

**Comment by innocces** [comment]
发现在这里看不到你的回复。邮件里有。我直接回复一下好了。主题样式覆盖应该是实时生效的。你可能需要检查一下你的引用位置。是不是没有被加载进来

**Comment by Tsukishima1** [comment]
> 发现在这里看不到你的回复。邮件里有。我直接回复一下好了。主题样式覆盖应该是实时生效的。你可能需要检查一下你的引用位置。是不是没有被加载进来

是的是的发了之后没多久就解决了所以删除了信息，感谢回复🙇🏻‍♀️
