### ISSUE TITLE
bug: 搜索框关闭按钮无效

### ISSUE THREAD

**Issue by Vincent-X** [innocces/dumi-theme-chakra#6]
### 版本

- dumi-theme-chakra: latest
- dumi: latest
- node:
- npm:
- OS: macOS
- Browser:

### 现有的现象？
搜索框关闭按钮无效

**Comment by innocces** [comment]
cmdk模式的搜索框中的x是清除搜索词的。关闭弹窗需点击遮罩。

**Comment by yutingzhao1991** [comment]
不得不说，这确实很像一个 bug，感觉可以优化下。

**Comment by innocces** [comment]
> 不得不说，这确实很像一个 bug，感觉可以优化下。

emmmm~ 可以提个pr
